### ISSUE TITLE
Everything in single line

### ISSUE THREAD

**Issue by RyanF109** [theZiz/aha#57] opened 2018-12-02 13:29 UTC
For some things passed to aha I get everything printed in a single line in the HTML where I would like the new lines to be printed. Am I missing something obvious?

```
$ df -l | aha
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- This file was created with the aha Ansi HTML Adapter. https://github.com/theZiz/aha -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="application/xml+xhtml; charset=UTF-8" />
<title>stdin</title>
</head>
<body>
<pre>
Filesystem     1K-blocks      Used Available Use% Mounted on
udev             2987924         0   2987924   0% /dev
tmpfs             603800      1768    602032   1% /run
/dev/sdb5      278083628  16868800 247019272   7% /
tmpfs            3018988        20   3018968   1% /dev/shm
tmpfs               5120         4      5116   1% /run/lock
tmpfs            3018988         0   3018988   0% /sys/fs/cgroup
/dev/loop7         14848     14848         0 100% /snap/gnome-logs/37
/dev/loop1         35584     35584         0 100% /snap/gtk-common-themes/319
/dev/loop0         13312     13312         0 100% /snap/gnome-characters/103
/dev/loop3        144384    144384         0 100% /snap/gnome-3-26-1604/70
/dev/loop5          2304      2304         0 100% /snap/gnome-calculator/260
/dev/loop2          3840      3840         0 100% /snap/gnome-system-monitor/51
/dev/loop6         14976     14976         0 100% /snap/gnome-logs/45
/dev/loop8         13312     13312         0 100% /snap/gnome-characters/139
/dev/loop10        35456     35456         0 100% /snap/gtk-common-themes/818
/dev/loop9         90368     90368         0 100% /snap/core/5897
/dev/loop12        89984     89984         0 100% /snap/core/5742
/dev/loop13         3840      3840         0 100% /snap/gnome-system-monitor/57
/dev/loop14        89088     89088         0 100% /snap/core/4917
/dev/loop4          2432      2432         0 100% /snap/gnome-calculator/180
/dev/loop11       144128    144128         0 100% /snap/gnome-3-26-1604/74
/dev/sdc2      732470268 257415360 475054908  36% /media/sys-storage
/dev/sdb1      201454560  75544748 115653432  40% /media/lin-storage
tmpfs             603796         4    603792   1% /run/user/1000
tmpfs             603796        12    603784   1% /run/user/121
</pre>
</body>
</html>

```

**Comment by theZiz** [comment] 2019-01-09 09:38
Hm, I cannot reproduce your problem – or I don't understand it. Can you give me a screenshot of the wrong behavior?

**Comment by lfshr** [comment] 2019-07-05 11:16
@theZiz I'm afraid @RyanF109, My brother, has since passed away. You can either attempt to reproduce this issue or close it. Thanks.

**Closed** 2019-09-19 07:25 UTC
